{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.vault.secretStore }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.path | quote }}
      version: {{ .Values.vault.version | quote }}
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.vault.role | quote }}
          serviceAccountRef:
            name: {{ .Values.vault.serviceAccount | quote }}
            namespace: {{ .Values.namespace | quote }}
{{- end }}
