{{- $mongo := .Values.oobeyaExternalMongo -}}
{{- $ns := .Values.namespace -}}

{{- if not $mongo.isExternal }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oobeyaMongo.secretName }}
  namespace: {{ $ns }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "oobeya"
  MONGO_INITDB_ROOT_PASSWORD: "mEQ9DwcmZSO8aXv9"
{{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oobeyaGateway.secretName }}
  namespace: {{ $ns }}
type: Opaque
stringData:
  {{- if $mongo.isExternal }}
  OOBEYA_GATEWAY_MONGODB_URI: "mongodb://{{ $mongo.user }}:{{ $mongo.pass }}@{{ $mongo.host }}:{{ $mongo.port }}/{{ $mongo.databases.gateway }}?authSource={{ $mongo.authSource }}"
  OOBEYA_GATEWAY_MONGODB_DB: {{ $mongo.databases.gateway | quote }}
  {{- else }}
  OOBEYA_GATEWAY_MONGODB_URI: "mongodb://oobeya:mEQ9DwcmZSO8aXv9@oobeya-mongo:27017/gatewayDB?authSource=admin"
  OOBEYA_GATEWAY_MONGODB_DB: "gatewayDB"
  {{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oobeyaAddons.secretName }}
  namespace: {{ $ns }}
type: Opaque
stringData:
  {{- if $mongo.isExternal }}
  ADDONS_MONGODB_URI: "mongodb://{{ $mongo.user }}:{{ $mongo.pass }}@{{ $mongo.host }}:{{ $mongo.port }}/{{ $mongo.databases.addons }}?authSource={{ $mongo.authSource }}"
  ADDONS_MONGODB_DB: {{ $mongo.databases.addons | quote }}
  {{- else }}
  ADDONS_MONGODB_URI: "mongodb://oobeya:mEQ9DwcmZSO8aXv9@oobeya-mongo:27017/addonsDB?authSource=admin"
  ADDONS_MONGODB_DB: "addonsDB"
  {{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oobeyaAgilespace.secretName }}
  namespace: {{ $ns }}
type: Opaque
stringData:
  {{- if $mongo.isExternal }}
  AGILESPACE_MONGODB_URI: "mongodb://{{ $mongo.user }}:{{ $mongo.pass }}@{{ $mongo.host }}:{{ $mongo.port }}/{{ $mongo.databases.agilespace }}?authSource={{ $mongo.authSource }}"
  AGILESPACE_MONGODB_DB: {{ $mongo.databases.agilespace | quote }}
  {{- else }}
  AGILESPACE_MONGODB_URI: "mongodb://oobeya:mEQ9DwcmZSO8aXv9@oobeya-mongo:27017/agilespaceDB?authSource=admin"
  AGILESPACE_MONGODB_DB: "agilespaceDB"
  {{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oobeyaDashboard.secretName }}
  namespace: {{ $ns }}
type: Opaque
stringData:
  {{- if $mongo.isExternal }}
  PLATFORM_MONGODB_URI: "mongodb://{{ $mongo.user }}:{{ $mongo.pass }}@{{ $mongo.host }}:{{ $mongo.port }}/{{ $mongo.databases.dashboard }}?authSource={{ $mongo.authSource }}"
  PLATFORM_MONGODB_DB: {{ $mongo.databases.dashboard | quote }}
  {{- else }}
  PLATFORM_MONGODB_URI: "mongodb://oobeya:mEQ9DwcmZSO8aXv9@oobeya-mongo:27017/dashboardDB?authSource=admin"
  PLATFORM_MONGODB_DB: "dashboardDB"
  {{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oobeyaDevteam.secretName }}
  namespace: {{ $ns }}
type: Opaque
stringData:
  {{- if $mongo.isExternal }}
  DEVTEAM_MONGODB_URI: "mongodb://{{ $mongo.user }}:{{ $mongo.pass }}@{{ $mongo.host }}:{{ $mongo.port }}/{{ $mongo.databases.devteam }}?authSource={{ $mongo.authSource }}"
  DEVTEAM_MONGODB_DB: {{ $mongo.databases.devteam | quote }}
  {{- else }}
  DEVTEAM_MONGODB_URI: "mongodb://oobeya:mEQ9DwcmZSO8aXv9@oobeya-mongo:27017/devteamDB?authSource=admin"
  DEVTEAM_MONGODB_DB: "devteamDB"
  {{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oobeyaGitwiser.secretName }}
  namespace: {{ $ns }}
type: Opaque
stringData:
  {{- if $mongo.isExternal }}
  GITWISER_MONGODB_URI: "mongodb://{{ $mongo.user }}:{{ $mongo.pass }}@{{ $mongo.host }}:{{ $mongo.port }}/{{ $mongo.databases.gitwiser }}?authSource={{ $mongo.authSource }}"
  GITWISER_MONGODB_DB: {{ $mongo.databases.gitwiser | quote }}
  {{- else }}
  GITWISER_MONGODB_URI: "mongodb://oobeya:mEQ9DwcmZSO8aXv9@oobeya-mongo:27017/gitwiserDB?authSource=admin"
  GITWISER_MONGODB_DB: "gitwiserDB"
  {{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oobeyaUaa.secretName }}
  namespace: {{ $ns }}
type: Opaque
stringData:
  {{- if $mongo.isExternal }}
  UAA_MONGODB_URI: "mongodb://{{ $mongo.user }}:{{ $mongo.pass }}@{{ $mongo.host }}:{{ $mongo.port }}/{{ $mongo.databases.uaa }}?authSource={{ $mongo.authSource }}"
  UAA_MONGODB_DB: {{ $mongo.databases.uaa | quote }}
  {{- else }}
  UAA_MONGODB_URI: "mongodb://oobeya:mEQ9DwcmZSO8aXv9@oobeya-mongo:27017/uaaDB?authSource=admin"
  UAA_MONGODB_DB: "uaaDB"
  {{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oobeyaRabbitmq.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.oobeyaRabbitmq.labels.app }}
type: Opaque
stringData:
  {{- if .Values.oobeyaExternalRabbitmq.isExternal }}
  RABBITMQ_HOST: {{ .Values.oobeyaExternalRabbitmq.external.host | quote }}
  RABBITMQ_PORT: {{ .Values.oobeyaExternalRabbitmq.external.port | quote }}
  RABBITMQ_USERNAME: {{ .Values.oobeyaExternalRabbitmq.external.user | quote }}
  RABBITMQ_PASSWORD: {{ .Values.oobeyaExternalRabbitmq.external.pass | quote }}
  SPRING_RABBITMQ_VIRTUAL_HOST: {{ .Values.oobeyaExternalRabbitmq.external.vhost | quote }}
  SPRING_RABBITMQ_SSL_ENABLED: {{ .Values.oobeyaExternalRabbitmq.external.ssl | quote }}
  SPRING_RABBITMQ_SSL_VALIDATE_SERVER_CERTIFICATE: {{ .Values.oobeyaExternalRabbitmq.external.sslVerify | quote }}
  {{- else }}
  RABBITMQ_HOST: {{ .Values.oobeyaExternalRabbitmq.internal.host | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.oobeyaExternalRabbitmq.internal.user | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.oobeyaExternalRabbitmq.internal.pass | quote }}
  {{- end }}
