apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oobeyaMongo.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.oobeyaMongo.labels.app }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: oobeya
  MONGO_INITDB_ROOT_PASSWORD: mEQ9DwcmZSO8aXv9

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oobeyaGateway.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.oobeyaGateway.labels.app }}
type: Opaque
stringData:
  OOBEYA_GATEWAY_MONGODB_URI: "mongodb://oobeya:mEQ9DwcmZSO8aXv9@oobeya-mongo:27017/gatewayDB?authSource=admin"
  OOBEYA_GATEWAY_MONGODB_DB: "gatewayDB"

---


apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oobeyaAddons.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.oobeyaAddons.labels.app }}
type: Opaque
stringData:
  ADDONS_MONGODB_URI: "mongodb://oobeya:mEQ9DwcmZSO8aXv9@oobeya-mongo:27017/addonsDB?authSource=admin"
  ADDONS_MONGODB_DB: "addonsDB"


---


apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oobeyaAgilespace.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.oobeyaAgilespace.labels.app }}
type: Opaque
stringData:
  AGILESPACE_MONGODB_URI: "mongodb://oobeya:mEQ9DwcmZSO8aXv9@oobeya-mongo:27017/agilespaceDB?authSource=admin"
  AGILESPACE_MONGODB_DB: "agilespaceDB"


---


apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oobeyaDashboard.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.oobeyaDashboard.labels.app }}
type: Opaque
stringData:
  PLATFORM_MONGODB_URI: "mongodb://oobeya:mEQ9DwcmZSO8aXv9@oobeya-mongo:27017/dashboardDB?authSource=admin"
  PLATFORM_MONGODB_DB: "dashboardDB"

---



apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oobeyaDevteam.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.oobeyaDevteam.labels.app }}
type: Opaque
stringData:
  DEVTEAM_MONGODB_URI: "mongodb://oobeya:mEQ9DwcmZSO8aXv9@oobeya-mongo:27017/devteamDB?authSource=admin"
  DEVTEAM_MONGODB_DB: "devteamDB"


---


apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oobeyaGitwiser.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.oobeyaGitwiser.labels.app }}
type: Opaque
stringData:
  GITWISER_MONGODB_URI: "mongodb://oobeya:mEQ9DwcmZSO8aXv9@oobeya-mongo:27017/gitwiserDB?authSource=admin"
  GITWISER_MONGODB_DB: "gitwiserDB"


---


apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oobeyaUaa.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.oobeyaUaa.labels.app }}
type: Opaque
stringData:
  UAA_MONGODB_URI: "mongodb://oobeya:mEQ9DwcmZSO8aXv9@oobeya-mongo:27017/uaaDB?authSource=admin"
  UAA_MONGODB_DB: "uaaDB"


